name: Deploy Images to GHCR

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
      push-image:
        runs-on: ubuntu-latest
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@main

          - name: Setup Gradle
            uses: gradle/gradle-build-action@v2
          - name: Make gradlew executable
            run: chmod +x ./gradlew
          - uses: actions/setup-java@v3

            with:

             distribution: 'zulu' # See 'Supported distributions' for available options

             java-version: '17'
          - name: Run build with Gradle Wrapper
            run: ./gradlew clean build -Pvaadin.productionMode --stacktrace

          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v1
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.GITHUB_TOKEN}}

          - name: 'Build Image'
            run: |
              docker build . --tag ghcr.io/matyrobbrt/website:latest
              docker push ghcr.io/matyrobbrt/website:latest
